2014-май-21 -> 11:36:58: 000003 run begin
2014-май-21 -> 11:36:59: 000003 : step_01 : 1asdasdas
2014-май-21 -> 11:36:59: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:36:59: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:36:59: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:36:59: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:36:59: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:36:59: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:36:59: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:36:59: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:36:59: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:36:59: 000003 run end
2014-май-21 -> 11:48:17: 000003 run begin
2014-май-21 -> 11:48:17: 000003 : step_01 : 1asdasdas
2014-май-21 -> 11:48:17: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:48:17: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:48:17: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:48:17: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:48:17: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:48:17: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:48:17: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:48:17: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:48:17: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:48:17: 000003 run end
2014-май-21 -> 11:51:02: 000003 run begin
2014-май-21 -> 11:51:02: 000003 : step_01 : 1asdasdas
2014-май-21 -> 11:51:02: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:51:02: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:51:02: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:51:02: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:51:02: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:51:02: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:51:02: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:51:02: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:51:02: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:51:02: 000003 run end
2014-май-21 -> 11:51:37: 000003 run begin
2014-май-21 -> 11:51:37: 000003 : step_01 : 1asdasdas
2014-май-21 -> 11:51:37: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:51:37: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:51:37: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:51:37: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:51:37: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:51:37: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:51:37: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:51:37: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:51:37: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:51:37: 000003 run end
2014-май-21 -> 11:52:54: 000003 run begin
2014-май-21 -> 11:52:54: 000003 : step_01 : 1asdasdas
2014-май-21 -> 11:52:54: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:52:54: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:52:54: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:52:54: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:52:54: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:52:54: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:52:54: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:52:54: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:52:54: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:52:54: 000003 run end
2014-май-21 -> 11:55:08: 000003 run begin
2014-май-21 -> 11:55:08: 000003 : step_01 : 1asdasdas
2014-май-21 -> 11:55:08: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:55:08: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:55:08: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:55:08: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:55:08: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:55:08: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:55:08: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:55:08: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:55:08: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:55:08: 000003 run end
2014-май-21 -> 11:56:17: 000003 run begin
2014-май-21 -> 11:56:17: 000003 : step_01 : 1asdasdas
2014-май-21 -> 11:56:17: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:56:17: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:56:17: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:56:18: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:56:18: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:56:18: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:56:18: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:56:18: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:56:18: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:56:18: 000003 run end
2014-май-21 -> 11:57:07: 000003 run begin
2014-май-21 -> 11:57:07: 000003 : step_01 : 1asdasdas
2014-май-21 -> 11:57:07: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:57:07: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:57:07: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:57:07: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:57:07: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:57:07: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:57:07: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:57:07: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:57:07: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:57:07: 000003 run end
2014-май-21 -> 11:58:05: 000003 run begin
2014-май-21 -> 11:58:05: 000003 : step_01 : 1asdasdas
2014-май-21 -> 11:58:05: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:58:05: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:58:05: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:58:05: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:58:05: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:58:05: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:58:05: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:58:05: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:58:05: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:58:05: 000003 run end
2014-май-21 -> 11:59:10: 000003 run begin
2014-май-21 -> 11:59:10: 000003 : step_01 : 1asdasdas
2014-май-21 -> 11:59:10: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:59:10: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:59:10: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:59:10: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:59:10: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:59:10: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:59:10: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:59:10: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:59:10: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:59:10: 000003 run end
2014-май-21 -> 11:59:50: 000003 run begin
2014-май-21 -> 11:59:50: 000003 : step_01 : 1asdasdas
2014-май-21 -> 11:59:50: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:59:50: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:59:50: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:59:50: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:59:50: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:59:50: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:59:50: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:59:50: 000003 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 11:59:50: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 11:59:50: 000003 run end
2014-май-21 -> 12:28:16: 254038 run begin
2014-май-21 -> 12:28:17: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:28:17: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:28:17: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:28:18: ORA-00904: "IS_SERVICE": invalid identifier

2014-май-21 -> 12:28:18: 254038 : step_02 : выборка тарифов годового контракта пустая
2014-май-21 -> 12:28:18: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 12:28:18: 254038 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 12:28:18: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 12:28:18: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 12:28:18: 254038 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 12:28:18: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 12:28:18: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 12:28:18: 254038 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 12:28:18: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 12:28:18: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 12:28:18: 254038 : След. шаг : Шаг не выполнялся, ошибка на предыдущем шаге
2014-май-21 -> 12:28:18: Ошибка: не найден номер шага в stacktrace. Возникает, когда появляется 'ошибка на предыдущем шаге', т.к. метод, описывающий шаг, не запускался, и соот-но его нет в stacktrace
2014-май-21 -> 12:28:18: 254038 run end
2014-май-21 -> 12:31:34: 254038 run begin
2014-май-21 -> 12:31:35: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:31:35: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:31:35: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:31:38: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:31:42: A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:7056/hub/session/fbcb1ca7-2fed-4825-9564-2382d20ae318/element. The status of the exception was ConnectionClosed, and the message was: Базовое соединение закрыто: Соединение было неожиданно закрыто.
2014-май-21 -> 12:31:42: Ссылка на объект не указывает на экземпляр объекта.
2014-май-21 -> 12:31:44: Unexpected error. System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:7056
   в System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   в System.Net.HttpWebRequest.GetRequestStream()
   в OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   в OpenQA.Selenium.Firefox.Internal.ExtensionConnection.Execute(Command commandToExecute)
   в OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2014-май-21 -> 12:31:46: Unexpected error. System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:7056
   в System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   в System.Net.HttpWebRequest.GetRequestStream()
   в OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   в OpenQA.Selenium.Firefox.Internal.ExtensionConnection.Execute(Command commandToExecute)
   в OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2014-май-21 -> 12:31:48: A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:7056/hub/session/fbcb1ca7-2fed-4825-9564-2382d20ae318/url. The status of the exception was ConnectFailure, and the message was: Невозможно соединиться с удаленным сервером
2014-май-21 -> 12:31:48: 254038 : step_06 : Некорректное имя сервиса [ожидаемо: at_loadservice_annual_105920078, актуально: Годовой контракт]
2014-май-21 -> 12:31:48: 254038 run end
2014-май-21 -> 12:31:54: 254038 run begin
2014-май-21 -> 12:31:55: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:31:55: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:31:55: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:32:00: 254038 : step_06 : Некорректное имя сервиса [ожидаемо: at_loadservice_annual_324413485, актуально: Годовой контракт]
2014-май-21 -> 12:32:00: 254038 run end
2014-май-21 -> 12:32:46: 254038 run begin
2014-май-21 -> 12:32:46: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:32:46: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:32:47: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:32:52: 254038 : step_06 : Некорректное имя сервиса [ожидаемо: at_loadservice_annual_1301893187, актуально: Годовой контракт]
2014-май-21 -> 12:32:52: 254038 run end
2014-май-21 -> 12:34:22: 254038 run begin
2014-май-21 -> 12:34:23: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:34:23: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:34:23: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:34:31: 254038 : step_06 : Некорректное имя сервиса [ожидаемо: at_loadservice_annual_1071006783, актуально: Годовой контракт]
2014-май-21 -> 12:34:31: 254038 run end
2014-май-21 -> 12:34:58: 254038 run begin
2014-май-21 -> 12:34:58: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:34:58: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:34:58: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:35:12: Unable to locate element: {"method":"xpath","selector":"(//input[@name='lid'])[5]"}
2014-май-21 -> 12:35:12: Ссылка на объект не указывает на экземпляр объекта.
2014-май-21 -> 12:35:14: A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:7056/hub/session/9ae0a08e-ff2a-48ba-b0f2-b90a56bcc1ff/element. The status of the exception was ConnectionClosed, and the message was: Базовое соединение закрыто: Соединение было неожиданно закрыто.
2014-май-21 -> 12:35:14: Ссылка на объект не указывает на экземпляр объекта.
2014-май-21 -> 12:35:18: Unexpected error. System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:7056
   в System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   в System.Net.HttpWebRequest.GetRequestStream()
   в OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   в OpenQA.Selenium.Firefox.Internal.ExtensionConnection.Execute(Command commandToExecute)
   в OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2014-май-21 -> 12:35:20: Unexpected error. System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:7056
   в System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   в System.Net.HttpWebRequest.GetRequestStream()
   в OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   в OpenQA.Selenium.Firefox.Internal.ExtensionConnection.Execute(Command commandToExecute)
   в OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2014-май-21 -> 12:35:20: Ссылка на объект не указывает на экземпляр объекта.
2014-май-21 -> 12:35:22: Unexpected error. System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:7056
   в System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   в System.Net.HttpWebRequest.GetRequestStream()
   в OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   в OpenQA.Selenium.Firefox.Internal.ExtensionConnection.Execute(Command commandToExecute)
   в OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2014-май-21 -> 12:35:24: Unexpected error. System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:7056
   в System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   в System.Net.HttpWebRequest.GetRequestStream()
   в OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   в OpenQA.Selenium.Firefox.Internal.ExtensionConnection.Execute(Command commandToExecute)
   в OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2014-май-21 -> 12:35:24: Ссылка на объект не указывает на экземпляр объекта.
2014-май-21 -> 12:35:26: A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:7056/hub/session/9ae0a08e-ff2a-48ba-b0f2-b90a56bcc1ff/url. The status of the exception was ConnectFailure, and the message was: Невозможно соединиться с удаленным сервером
2014-май-21 -> 12:35:26: 254038 : step_06 : Некорректное имя сервиса [ожидаемо: at_loadservice_annual_494524704, актуально: Годовой контракт]
2014-май-21 -> 12:35:26: 254038 run end
2014-май-21 -> 12:35:32: 254038 run begin
2014-май-21 -> 12:35:33: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:35:33: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:35:33: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:35:35: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:35:35: A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:7056/hub/session/8e36e505-26bb-462b-9243-dd569d0c1e82/element. The status of the exception was ConnectionClosed, and the message was: Базовое соединение закрыто: Соединение было неожиданно закрыто.
2014-май-21 -> 12:35:35: Ссылка на объект не указывает на экземпляр объекта.
2014-май-21 -> 12:35:38: Unexpected error. System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:7056
   в System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   в System.Net.HttpWebRequest.GetRequestStream()
   в OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   в OpenQA.Selenium.Firefox.Internal.ExtensionConnection.Execute(Command commandToExecute)
   в OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2014-май-21 -> 12:35:40: Unexpected error. System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:7056
   в System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   в System.Net.HttpWebRequest.GetRequestStream()
   в OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   в OpenQA.Selenium.Firefox.Internal.ExtensionConnection.Execute(Command commandToExecute)
   в OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2014-май-21 -> 12:35:42: A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:7056/hub/session/8e36e505-26bb-462b-9243-dd569d0c1e82/url. The status of the exception was ConnectFailure, and the message was: Невозможно соединиться с удаленным сервером
2014-май-21 -> 12:35:42: 254038 : step_06 : Некорректное имя сервиса [ожидаемо: at_loadservice_annual_365562394, актуально: Годовой контракт]
2014-май-21 -> 12:35:42: 254038 run end
2014-май-21 -> 12:37:57: 254038 run begin
2014-май-21 -> 12:37:57: ORA-00920: invalid relational operator

2014-май-21 -> 12:38:02: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:38:12: Unable to locate element: {"method":"xpath","selector":"(//a[contains(@href, '#internet')])[2]"}
2014-май-21 -> 12:38:12: Ссылка на объект не указывает на экземпляр объекта.
2014-май-21 -> 12:38:12: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:38:22: Unable to locate element: {"method":"xpath","selector":"(//select[@name='action'])[4]"}
2014-май-21 -> 12:38:23: 254038 : step_06 : Некорректное имя сервиса [ожидаемо: at_loadservice_annual_1757163332, актуально: Годовой контракт]
2014-май-21 -> 12:38:23: 254038 run end
2014-май-21 -> 12:38:40: 254038 run begin
2014-май-21 -> 12:38:40: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:38:40: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:38:40: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:38:57: Unable to locate element: {"method":"xpath","selector":"(//input[@name='lid'])[5]"}
2014-май-21 -> 12:38:57: Ссылка на объект не указывает на экземпляр объекта.
2014-май-21 -> 12:39:07: A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:7057/hub/session/1e027ee8-85af-4d7e-9c52-01b1928ac4f7/element. The status of the exception was ConnectionClosed, and the message was: Базовое соединение закрыто: Соединение было неожиданно закрыто.
2014-май-21 -> 12:39:07: Ссылка на объект не указывает на экземпляр объекта.
2014-май-21 -> 12:39:11: Unexpected error. System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:7057
   в System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   в System.Net.HttpWebRequest.GetRequestStream()
   в OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   в OpenQA.Selenium.Firefox.Internal.ExtensionConnection.Execute(Command commandToExecute)
   в OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2014-май-21 -> 12:39:13: Unexpected error. System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:7057
   в System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   в System.Net.HttpWebRequest.GetRequestStream()
   в OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   в OpenQA.Selenium.Firefox.Internal.ExtensionConnection.Execute(Command commandToExecute)
   в OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2014-май-21 -> 12:39:13: Ссылка на объект не указывает на экземпляр объекта.
2014-май-21 -> 12:39:15: Unexpected error. System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:7057
   в System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   в System.Net.HttpWebRequest.GetRequestStream()
   в OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   в OpenQA.Selenium.Firefox.Internal.ExtensionConnection.Execute(Command commandToExecute)
   в OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2014-май-21 -> 12:39:17: Unexpected error. System.Net.WebException: Невозможно соединиться с удаленным сервером ---> System.Net.Sockets.SocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:7057
   в System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   в System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   в System.Net.HttpWebRequest.GetRequestStream()
   в OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   в OpenQA.Selenium.Firefox.Internal.ExtensionConnection.Execute(Command commandToExecute)
   в OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2014-май-21 -> 12:39:17: Ссылка на объект не указывает на экземпляр объекта.
2014-май-21 -> 12:39:17: 254038 run end
2014-май-21 -> 12:39:27: 254038 run begin
2014-май-21 -> 12:39:28: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:39:28: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:39:28: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-21 -> 12:39:35: 254038 run end
2014-май-22 -> 03:50:01: 000003 run begin
2014-май-22 -> 05:34:02: 253992 run begin
2014-май-22 -> 05:34:02: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:34:03: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:34:03: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:34:17: Unable to locate element: {"method":"xpath","selector":"(//select[@name='action'])[5]"}
2014-май-22 -> 05:35:22: 254236 run begin
2014-май-22 -> 05:35:22: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:35:22: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:35:23: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:40:48: 254236 run begin
2014-май-22 -> 05:40:49: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:40:49: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:40:49: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:41:11: 254236 run end
2014-май-22 -> 05:53:33: 254244 run begin
2014-май-22 -> 05:53:34: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:53:34: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:53:34: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:53:39: Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
Имя параметра: index
2014-май-22 -> 05:53:39: 254244 : step_07 : загруженный сервис отсутствует в БД (выборка пустая)
2014-май-22 -> 05:53:39: 254244 run end
2014-май-22 -> 05:54:23: 254244 run begin
2014-май-22 -> 05:54:24: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:54:24: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:54:24: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:55:05: 254244 run begin
2014-май-22 -> 05:55:06: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:55:06: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:55:07: jQuery is not defined (UnexpectedJavaScriptError)
2014-май-22 -> 05:55:20: 254244 run end
